#!/bin/bash
logger=/home/onikenx/.var/logs/mounts/mega

echo -e "\n\t==== $(date) ====\n" >> $logger

rclone mount onedrive: /home/onikenx/Clouds/OneDrive/ --vfs-cache-mode writes >> $logger 2>> $logger &
