#!/bin/bash
WINE=${WINE:-wine}
WINEPREFIX=${WINEPREFIX:-$HOME/.local/share/wineprefixes/windev/}
export WINEPREFIX
PROGRAMFILES="z:\media\windows\Program Files (x86)"
WSDK="$PROGRAMFILES\Microsoft Visual Studio\2019\Community"
export WINEPATH="c:\windows;c:\windows\system32;$WSDK\Common7\IDE;$WSDK\VC\bin"
export INCLUDE="$WSDK\VC\include;$WPSDK\Include"
LIB="$WSDK\VC\lib;$WPSDK\Lib"
wine cl.exe $@

#WPSDK="$PROGRAMFILES\Microsoft SDKs\Windows\v7.1
#WDXSDK="$PROGRAMFILES\Microsoft DirectX SDK (August 2006)"
#;$WDXSDK\Include
#;$WDXSDK\Lib\x86
