#!/bin/bash
echo "Arch repositories and AUR:"
yay --pacman powerpill -Syu --noconfirm
echo
echo "Flatpak:"; sudo flatpak update -y
echo
echo "pipx upgrade: ";pipx upgrade-all
echo
echo "npm upgrade:"; npm update -g
echo
echo "Proton-GE:";updatePGEfast
echo
echo "Ruby Bundle:"; gem update
